find_program(CCACHE_FOUND ccache)
if(CCACHE_FOUND)
    Log("Using ccache")
    set_property(GLOBAL PROPERTY RULE_LAUNCH_COMPILE ccache)
    set_property(GLOBAL PROPERTY RULE_LAUNCH_LINK ccache)
else()
    Log("WARNING: ccache does not working")
endif(CCACHE_FOUND)
